company_suffixes:
  - Limited
  - Ltd
  - Pvt
  - PLC
  - Corporation
  - Company
  - Industries
  - Bank
  - Asset Management
  - Holdings
  - Group
  - Systems
  - Finance
  - Projects
  - Chemicals
  - Motors