# .github/workflows/ci.yml
# Basic CI for AI Stock Picker (Python, uv, Poetry)
name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install uv
        run: pip install uv
      - name: Install dependencies (uv)
        run: uv pip install -r requirements.txt
      - name: Install Poetry
        run: pip install poetry
      - name: Poetry install (optional)
        run: poetry install
      - name: Run tests
        run: pytest tests/
      - name: Black format check
        run: black --check .
      - name: Type check
        run: mypy .
      - name: Lint (optional)
        run: |
          pip install flake8
          flake8 .